adding some field
yazdan/career-path pull request #9
Opened 2017-12-29 20:46 UTC by Arshiamidos

اضافه کردن
بلاک چین
محاسبات نرم 
هوش مصنوعی
مهارت های بازی سازی

2017-12-29 21:42 UTC, yazdan requested changes
اول از همه دست شما درد نکنه
به نظرم یه سری از این موارد در حال حاضر عنوان مستقیمی نداره
قسمت بازی هم بهتره با تغییرات #8  چک بشه

2017-12-29 21:42 UTC, yazdan commented on README.md
> +    * [توسعه‌دهنده هوش‌مصنوعی](#توسعه‌دهنده هوش‌مصنوعی)
این واقعا یک نوع توسعه دهنده است؟ من توی شرکت‌های خارجی یه چنین چیزی ندیدم
اگه هست بگید تا منم آشنا بشم

2017-12-29 21:42 UTC, yazdan commented on README.md
> +    * [توسعه‌دهنده‌ی بلاک‌چین](#توسعه‌دهنده‌ی بلاک‌چین)
این واقعا یک نوع توسعه دهنده است؟ من توی شرکت‌های خارجی یه چنین چیزی ندیدم
اگه هست بگید تا منم آشنا بشم

2017-12-29 21:42 UTC, yazdan commented on README.md
> +    * [توسعه‌دهنده‌ی محاسبات‌ابری](#توسعه‌دهنده‌ی محاسبات‌ابری)
این واقعا یک نوع توسعه دهنده است؟ من توی شرکت‌های خارجی یه چنین چیزی ندیدم
اگه هست بگید تا منم آشنا بشم

2017-12-29 21:42 UTC, yazdan commented on README.md
> +مهارت‌ها
اینها رو با تغییراتی که عرفان بشارت توی #8  داده یه چکی کنید شاید تداخل داشته باشه

2017-12-30 08:12 UTC, Arshiamidos commented on README.md
> +    * [توسعه‌دهنده هوش‌مصنوعی](#توسعه‌دهنده هوش‌مصنوعی)
خب راستش شرکت های زیادی وجود دارن توی ایران و خارج که روی مباحث هوش مصنوعی کار میکنن که یکی از شاخه هاش میشه رباتیک!! البته دیدگاه من اینه که توی دانشگاه هم رشتش هس 
البته مباحث بلاک چین و کاربرداش تازه وارد شده ولی مثل 
JS
هنوز جای رشد داره 
.

2018-01-01 20:16 UTC, merged